name: Update Current Projects

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:

  update:

    name: Update Age
    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Update current projects in Readme
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python3 scripts/latest-projects.py

      - name: Commit & Push
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: update latest projects
          branch: master